neos/redirecthandler-neosadapter

Classes/Service/NodeRedirectService.php

Create redirects with correct ``sourceUri`` if a fallback dimension is present for the current node. Before this fix the ``uriSegment`` from the fallback dimension was used for the current node and wrong redirects where created for the node and all it's children.
Fixes: #9

BUGFIX: Create redirects with correct ``sourceUri``

---

Classes/Service/NodeRedirectService.php

This is related to a change in Neos (PR #606). Since 2013 the hostPattern
no longer supported using a wildcard.
This change renames getHostPatterns to getHostnames. It therefore makes
things clearer.

TASK: Rename getHostPatterns to getHostnames

---

Classes/Service/NodeRedirectService.php

Sometimes nodes disappeared from DB because during creating redirect links
something stops working and it ruins the site nodes.
This wraps the existing function `createRedirectsForPublishedNode` with
`try...catch` to make sure that missing redirect features don't break the node
structure. It adds logging the error instead.

BUGFIX: Fix the redirect error when copying a subtree

---

Classes/Service/NodeRedirectService.php
Configuration/Settings.yaml

With this change it is possible to implement a custom node removed handling for custom NodeTypes.
For example if a product Document node is deleted you are now able to implement a custom redirect to the parent list of the product instead to just have a redirect to 404.

Configurable node isRemoved handling

---

.travisci.yml
Classes/Service/NodeRedirectService.php
Tests/Functional/Service/NodeRedirectServiceTest.php

This prevents the same node in contexts differing only in visibility
properties from having different paths during comparison.
The previous behavior led to erratic redirects being created when moving a document deeper into the tree, then back to its original position and so on

BUGFIX: Fix node URI path comparison

---

.styleci.yml
Classes/Service/NodeRedirectService.php
composer.json

Also create redirects for nodes that are not persisted as an independent node within the CR, but used a node within a fallback dimension that "shined" through.
For all independent nodes within other dimensions the "publish" signal is called separately when the user clicks "publish all" and the behavior is already correct.

BUGFIX: Fix behaviour for fallback dimensions

---

Configuration/Settings.yaml

The configuration key was renamed in https://github.com/neos/redirecthandler-neosadapter/commit/59ba3e4606c76c3d150c076091c09636c0d5a41f
Resolves: #43

BUGFIX: Adjust settings to renamed config

---

Classes/Package.php
Configuration/Settings.yaml
Documentation/index.rst

This is helpful for any cli actions, large imports etc.
On cli you can get exceptions due to missing HttpRequest.
And in large import scenarios the Slot for allObjectsPersisted signal
can slow down the import process.
Explicitly disabling automatic redirects deems more intuitive than
implicitly enabling it - you have to know what you are doing.
This is why we put in a disable* setting instead of an enable* setting

FEATURE: Completely disable automatic generation

---

Documentation/index.rst

I had trouble configuring the restriction of nodetypes because the configuration was implicitly suggesting that `restrictByNodeType` should be placed directly below
```yaml
Neos:
RedirectHandler:
```
, because there is no mention of the intermediary key `NeosAdapter` where the php code reads the config from. So I added the correct config path to the examples.
I also tried to clarify how the restriction works after I tested and understood it: It's a black list and - other than one might think - using `true` as the config value does not whitelist ist. It actually adds it to the blacklist :)

Clarify how to restrict redirect generation

---

composer.json

Currently redirecthandler cannot be installed on master.

Relax version constraint to allow dev-master for neos and redirecthandler

---

.github/workflows/tests.yml
Classes/Service/NodeRedirectService.php
Configuration/Settings.yaml
Documentation/index.rst
Tests/Behavior/Features/Bootstrap/FeatureContext.php
Tests/Behavior/Features/Bootstrap/RedirectOperationTrait.php
Tests/Behavior/behat.yml
Tests/Behavior/behat.yml.dist
Tests/Functional/Service/NodeRedirectServiceTest.php

Without this change the redirect generation was not possible
f.e. when `flow workspace:publish` was used to publish a
workspace. The necessary http request to build uris was
not available.
Resolves: #41
I check if the current request is from a CommandController a custom request ist built.
Flow baseUri setting or simply localhost is used as baseUri. But this uri does not really matter
as this change also now uses a nodes context for generating the direct.
This means the domain of the site a node is in will be used to define the host parameter
for a redirect. So multi-site installations will now receive the proper host for each redirect.
This should also improve the behaviour when publishing nodes from multiple sites at the same time via the backend.
If no domain is set, the redirect will …

FEATURE: Allow automatic redirect generation for CLI publishing

---

Classes/Service/NodeRedirectService.php

Fixes: #61
There are two cases when the uri changes for the current node. Either the uriPathSegment has changed or it was moved, meaning the parentPath changed.
In our case, the publish time was reduced from 45 seconds to 3 seconds.

BUGFIX: Simplify and fix hasNodeUriChanged

---

.github/workflows/tests.yml
Classes/CatchUpHook/DocumentUriPathProjectionHook.php
Classes/CatchUpHook/DocumentUriPathProjectionHookFactory.php

Removes unused ContentRepositoryRegistry from hook

TASK: Remove unused registry

---

Classes/Service/NodeRedirectService.php

Using `#[Flow\inject]` on a constructor parameter fails with `Attribute "Neos\Flow\Annotations\Inject" cannot target parameter (allowed targets: property)`.

BUGFIX: Fix constructor injection in `NodeRedirectService`

---

Classes/Service/NodeRedirectService.php
Tests/Behavior/Features/Bootstrap/FeatureContext.php

Relates: neos/neos-development-collection#4891
Relates: neos/neos-ui#3717

TASK: Adjust to movement of `ContentRepositoryId` to `SharedModel` namespace

---

.github/workflows/tests.yml
Classes/CatchUpHook/DocumentUriPathProjectionHook.php
Tests/Behavior/Features/Bootstrap/FeatureContext.php
Tests/Behavior/Features/Bootstrap/RedirectOperationTrait.php
Tests/Behavior/Features/MultipleDimensions.feature
Tests/Behavior/Features/OneDimension.feature
Tests/Behavior/Features/WithoutDimensions.feature
composer.json

The way how we write behat tests has undergone major changes via `neos/behat` and the runtime helpers in Neos as well.
For example we use workspace names now and dont block anymore.
Resolves: #76

BUGFIX: Repair behat tests and Neos9-Beta-10 compatibility

---

Classes/CatchUpHook/DocumentUriPathProjectionHook.php

Adjustments for https://github.com/neos/neos-development-collection/pull/5149

TASK: Check against LiveWorkspaceName Instead Of Comparing CS Ids

---

Classes/CatchUpHook/DocumentUriPathProjectionHook.php

when moving among siblings, the URI does not change, so no redirect has to be handled

only react on NodeAggregateWasMoved when there is a new parent

---

Classes/CatchUpHook/DocumentUriPathProjectionHook.php
Classes/CatchUpHook/DocumentUriPathProjectionHookFactory.php

see https://github.com/neos/neos-development-collection/pull/5328

TASK: Adjust to use `CatchUpHookFactoryDependencies`

---

Classes/CatchUpHook/DocumentUriPathProjectionHook.php
Classes/CatchUpHook/DocumentUriPathProjectionHookFactory.php
Tests/Behavior/Features/Bootstrap/FeatureContext.php

https://github.com/neos/neos-development-collection/pull/5321

TASK: Adjust to subscription engine
